### ISSUE TITLE
Weird Right Click

### ISSUE THREAD

**Issue by cetinodinson** [typeling1578/MaterialFox-Plus#1]
Hi, I tried your userchrome.css which is looking so nice; but there is a graphical error on right click I think. 
Windows 7 64bit with Firefox ESR

![Screenshot_1](https://user-images.githubusercontent.com/70116455/150614192-805c3083-3c84-42c7-88a4-baa2af765d92.jpg)
.

**Comment by typeling1578** [comment]
Is it ESR91?

**Comment by typeling1578** [comment]
I don't have Windows 7, so I cannot fix it.
If you are able to fix it, it would be great if you could send a pull request to this repository.

**Comment by typeling1578** [comment]
We have decided to end support for Windows 7, so we are closing the Issue.
https://github.com/typeling1578/MaterialFox-Plus/commit/4af6d88853bebe10647e25df9251d5fdb731618a
