### ISSUE TITLE
End of support for Windows 7.

### ISSUE THREAD

**Issue by typeling1578** [typeling1578/MaterialFox-Plus#2]
I do not have a Windows 7 environment, so I cannot confirm that it works on Windows 7.
Therefore, I am considering ending support for Windows 7.

**Comment by typeling1578** [comment]
#1

**Comment by typeling1578** [comment]
https://github.com/typeling1578/MaterialFox-Plus/commit/4af6d88853bebe10647e25df9251d5fdb731618a

**Comment by Davilarek** [comment]
why not try in virtual machine?

**Comment by typeling1578** [comment]
My PC does not have enough capacity to run Windows 7 in a virtual machine.
Also, please do not continue to use an OS for which security updates are no longer being distributed.
