### ISSUE TITLE
Line Between Multiple Tabs is Very High for Some Reason

### ISSUE THREAD

**Issue by featherie** [typeling1578/MaterialFox-Plus#7]
I'm unsure if this was something I accidentally messed up myself or if a bug caused this, but it seems like the lines in between multiple tabs go off the screen/aren't vertically centered for some reason. Thanks!
Firefox:
![image](https://user-images.githubusercontent.com/120501337/207406564-96e23759-35c4-49bb-ab84-a1a12841fba7.png)
Chrome:
![image](https://user-images.githubusercontent.com/120501337/207406690-55439a32-c166-449b-831b-7c2d1403b76c.png)

**Comment by s1h4d0w** [comment]
Having the same issue, glad someone else already posted. Just appeared today after a reboot of my machine, probably after a Windows 11 update.

**Comment by DoNotResuscitate** [comment]
Yup also noticing this now

**Comment by zhouhaibing089** [comment]
https://github.com/M0kh/MaterialFox-Updated/commit/4444b10bd2ccb0c7edc78c28faddf7630afd6ad0 seems to have fixed this issue for me.

**Comment by Radplay** [comment]
> [M0kh@4444b10](https://github.com/M0kh/MaterialFox-Updated/commit/4444b10bd2ccb0c7edc78c28faddf7630afd6ad0) seems to have fixed this issue for me.

For me it didn't, it only shifted the line down a bit
